# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Hadrien Gourlé
tagline:          ''
description:      'PhD student in bioinformatics in Uppsala, Sweden'
url:              http://hadriengourle.com
baseurl:          /

author:
  name:           'Hadrien Gourlé'
  url:            http://hadriengourle.com

paginate:         5

github:
  repo:           https://github.com/HadrienG
